r = input("Enter value of r : ");
theta = 0:(%pi/16):(2*(%pi));
x = r*cos(theta);
y = r*sin(theta);
figure(0);
clf(0);
plot(x,y);
sleep(2000);
xlabel("X");
ylabel("Y");
title("Plot of circle : figure(0)");
figure(1);
clf(1);
plot(x,y,'o');
xlabel("X");
ylabel("Y");
title("Plot of circle : Distinct points :figure(1)");
sleep(2000);
figure(2);
clf(2);
xlabel("X");
ylabel("Y");
title("Plot of circles : Combined :figure(2) = Fig(1) + Fig(2)");
plot(x,y);
plot(x,y,'o');
